### ISSUE TITLE
建议文章中的代码给出完整的代码

### ISSUE THREAD

**Issue by wangjia2016** [keets2012/Auth-service#1]
![image](https://user-images.githubusercontent.com/16084076/32429863-86d277b2-c307-11e7-8f1f-bb3a6272891b.png)

覆写方法，这个代码块没看到父类是哪个，因此对于新手来说有点糊

**Comment by keets2012** [comment]
实现的是AuthorizationServerConfigurer接口，完整代码要把网关讲完，补上demo，再一起公开。欢迎关注

**Comment by keets2012** [comment]
请关注下整合项目。
