### ISSUE TITLE
/oauth/token   401 Unauthorized

### ISSUE THREAD

**Issue by HanWang945** [keets2012/Auth-service#12]
post:
      http://localhost:10101/login/oauth/token?grant_type=password&username=keets&password=password&client=frontend
返回：
  {
    "timestamp": "2019-06-22T09:06:35.172+0000",
    "status": 401,
    "error": "Unauthorized",
    "message": "Unauthorized",
    "path": "/oauth/token"
}
或者 post  http://localhost:10101/oauth/token?grant_type=password&username=keets&password=password&client=frontend
则出现：
{
    "error": "unauthorized",
    "error_description": "Full authentication is required to access this resource"
}

**Comment by keets2012** [comment]
请求的body提供一下？

**Comment by telami** [comment]
> post:
> http://localhost:10101/login/oauth/token?grant_type=password&username=keets&password=password&client=frontend
> 返回：
> {
> "timestamp": "2019-06-22T09:06:35.172+0000",
> "status": 401,
> "error": "Unauthorized",
> "message": "Unauthorized",
> "path": "/oauth/token"
> }
> 或者 post http://localhost:10101/oauth/token?grant_type=password&username=keets&password=password&client=frontend
> 则出现：
> {
> "error": "unauthorized",
> "error_description": "Full authentication is required to access this resource"
> }

很常见的问题，请求头没传Basic认证信息，也就是clientId+clientSecret的base64编码

**Comment by keets2012** [comment]
正解 @telami
